-- ============================================================
-- MIGRATION: 016_proactive_scheduler_and_facts.sql
-- Adds proactivity scheduling infrastructure and fact extraction
-- ============================================================

-- ============================================================
-- Table: proactive_suggestions
-- Stores time-triggered suggestions generated by the scheduler.
-- Includes overdue action items, deadline warnings, cross-doc
-- connections, and general proactivity nudges.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.proactive_suggestions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    category TEXT NOT NULL,  -- 'overdue_task', 'upcoming_deadline', 'cross_doc_connection', 'decision_gap', 'scheduled_action'
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'medium',  -- 'high', 'medium', 'low'
    source_entity_type TEXT,  -- 'action_item', 'meeting', 'document', 'decision'
    source_entity_id TEXT,
    metadata JSONB DEFAULT '{}',
    is_dismissed BOOLEAN DEFAULT false,
    is_viewed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_proactive_suggestions_tenant ON public.proactive_suggestions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_proactive_suggestions_user ON public.proactive_suggestions(user_id);
CREATE INDEX IF NOT EXISTS idx_proactive_suggestions_status ON public.proactive_suggestions(tenant_id, is_dismissed, is_viewed);
CREATE INDEX IF NOT EXISTS idx_proactive_suggestions_priority ON public.proactive_suggestions(tenant_id, priority, created_at DESC);

-- Enable RLS
ALTER TABLE public.proactive_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view proactive suggestions in their company" ON public.proactive_suggestions
    FOR SELECT USING (
        tenant_id = (auth.jwt() ->> 'company_id')::uuid
    );

CREATE POLICY "Users can manage proactive suggestions in their company" ON public.proactive_suggestions
    FOR ALL USING (
        tenant_id = (auth.jwt() ->> 'company_id')::uuid
    );

-- ============================================================
-- Table: scheduler_state
-- Tracks when each company was last scanned by the proactivity
-- scheduler. Enables incremental scanning — only companies that
-- haven't been scanned recently get re-scanned.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.scheduler_state (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE UNIQUE,
    last_full_scan TIMESTAMP WITH TIME ZONE,
    last_overdue_scan TIMESTAMP WITH TIME ZONE,
    last_cross_doc_scan TIMESTAMP WITH TIME ZONE,
    last_deadline_scan TIMESTAMP WITH TIME ZONE,
    scan_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.scheduler_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role manages scheduler state" ON public.scheduler_state
    FOR ALL USING (true);

-- ============================================================
-- Table: key_facts
-- Stores extracted facts from conversations for cross-session
-- memory. Facts persist across chat sessions so the Brain
-- remembers key information about the person, company, and work.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.key_facts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    session_id TEXT,
    fact TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'general',  -- 'personal', 'project', 'decision', 'preference', 'deadline', 'relationship', 'general'
    confidence FLOAT DEFAULT 0.8,  -- 0.0 to 1.0
    source_message TEXT,
    is_active BOOLEAN DEFAULT true,  -- soft-delete for outdated facts
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_key_facts_tenant_user ON public.key_facts(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_key_facts_active ON public.key_facts(tenant_id, user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_key_facts_category ON public.key_facts(tenant_id, category);

-- Enable RLS
ALTER TABLE public.key_facts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view key facts in their company" ON public.key_facts
    FOR SELECT USING (
        tenant_id = (auth.jwt() ->> 'company_id')::uuid
    );

CREATE POLICY "Users can manage key facts in their company" ON public.key_facts
    FOR ALL USING (
        tenant_id = (auth.jwt() ->> 'company_id')::uuid
    );
